### ISSUE TITLE
Unable to run documentation locally due to missing dependencies and build errors

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-auth#76]
I am trying to run the documentation locally for the project following the steps outlined in the [Installation Guide](https://github.com/openmobilehub/react-native-omh-auth/tree/main/docs#installation) and encountering multiple errors. I used Yarn (4.2.2) and Bun (1.1.8) with the following results:

### Steps to Reproduce:
1. Clone the repository.
2. Navigate to the `docs` directory.
3. Run `yarn install`.
4. Run `yarn build`.

### Errors:
**Running `yarn build` returns the following errors:**
```
[INFO] [en] Creating an optimized production build...
[info] Loaded plugin typedoc-plugin-markdown
[info] Loaded plugin typedoc-plugin-replace-text
../packages/plugin-dropbox/src/index.tsx:6:32 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

6 import {createAuthModule} from '@openmobilehub/auth-core';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-dropbox/src/IOSGetUser.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

...

[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/xxxx/tools/git/react-native-omh-auth/node_modules/@docusaurus/core/lib/commands/build.js:53:19)
xx    at async mapAsyncSequential (/Users/xxx/tools/git/react-native-omh-auth/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/Users/xxxx/tools/git/react-native-omh-auth/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
  [cause]: Error: Docusaurus static site generation failed for 10 paths:
  - "/react-native-omh-auth/404.html"
  - "/react-native-omh-auth/"
  ...
```

**Running `yarn install` returns the following errors:**
```
yarn install
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 277ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ @openmobilehub/auth-core@workspace:packages/core doesn't provide react (p350d4), requested by react-native.
➤ YN0002: │ @openmobilehub/auth-dropbox@workspace:packages/plugin-dropbox doesn't provide react (p0c2d0), requested by react-native.
➤ YN0002: │ @openmobilehub/auth-facebook@workspace:packages/plugin-facebook doesn't provide react (p1b32a), requested by react-native.
➤ YN0002: │ @openmobilehub/auth-google@workspace:packages/plugin-google doesn't provide react (pfdb07), requested by react-native.
➤ YN0002: │ @openmobilehub/auth-microsoft@workspace:packages/plugin-microsoft doesn't provide react (pf66fd), requested by react-native.
➤ YN0002: │ docs@workspace:docs doesn't provide @types/react (p81cbc), requested by @mdx-js/react.
➤ YN0002: │ react-native-omh-auth@workspace:. doesn't provide prettier (p52c2f), requested by @ianvs/prettier-plugin-sort-imports.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
```

### Observations:
- It appears that the build process is failing due to missing dependencies related to `@openmobilehub/auth-core`.
- The `yarn install` command highlights missing peer dependencies for various packages.
- It is worth noting that the GitHub Actions workflow runs successfully, which adds to the confusion.

Could you please look into this issue and update the documentation or the build scripts to ensure that all dependencies are correctly installed and the documentation can be built locally without errors?

### Environment:
- **OS:** macOS
- **Node Version:** 18.x
- **Yarn Version:** 4.2.2
- **Bun Version:** 1.1.8

Thank you for your assistance!

**Comment by andrei-zgirvaci** [comment]
Hi @dzuluaga, could you try to run `yarn workspace docs start` from the root project directory? We have it documented in the [Contributing Guide - Writing Documentation](https://github.com/openmobilehub/react-native-omh-auth/blob/main/CONTRIBUTING.md#writing-documentation) section.

**Comment by dzuluaga** [comment]
Similar errors:

```
react-native-omh-auth git:(main) ✗ yarn workspace docs start

    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------

                                                                       Update available 3.2.1 → 3.4.0

                                              To upgrade Docusaurus packages with the latest version, run the following command:
         `npm i @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest @docusaurus/tsconfig@latest @docusaurus/types@latest`

    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------

[INFO] Starting the development server...
[info] Loaded plugin typedoc-plugin-markdown
[info] Loaded plugin typedoc-plugin-replace-text
../packages/plugin-dropbox/src/index.tsx:6:32 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

6 import {createAuthModule} from '@openmobilehub/auth-core';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-dropbox/src/IOSGetUser.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-dropbox/src/IOSRefreshAccessToken.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-dropbox/src/IOSRevokeAccessToken.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-facebook/src/index.tsx:6:32 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

6 import {createAuthModule} from '@openmobilehub/auth-core';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-facebook/src/IOSGetUser.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-facebook/src/IOSRefreshAccessToken.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-facebook/src/IOSRevokeAccessToken.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-google/src/index.tsx:6:32 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

6 import {createAuthModule} from '@openmobilehub/auth-core';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-google/src/IOSGetUser.ts:1:41 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

1 import type {AuthConfig, AuthData} from '@openmobilehub/auth-core';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-microsoft/src/index.tsx:6:32 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

6 import {createAuthModule} from '@openmobilehub/auth-core';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-microsoft/src/IOSGetUser.ts:5:8 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

5 } from '@openmobilehub/auth-core';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~

../packages/plugin-microsoft/src/types.ts:4:8 - error TS2307: Cannot find module '@openmobilehub/auth-core' or its corresponding type declarations.

4 } from '@openmobilehub/auth-core';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~

[WARNING] No docs found in "api": can't auto-generate a sidebar.
[SUCCESS] Docusaurus website is running at: http://localhost:3000/react-native-omh-auth/

● Client █████████████████████████ building (10%) 0/3 entries 27/41 dependencies 5/19 modules 10 active
 ../node_modules/webpack-dev-server/client/clients/WebSocketClient.js


[ERROR] file:///Users/xxx/tools/git/react-native-omh-auth/node_modules/babel-loader/node_modules/find-up/index.js:3
import {locatePath, locatePathSync} from 'locate-path';
        ^^^^^^^^^^
SyntaxError: Named export 'locatePath' not found. The requested module 'locate-path' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'locate-path';
const {locatePath, locatePathSync} = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

And `yarn build` generates this error:

```
yarn build
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + turbo@npm:2.0.4, turbo-darwin-64@npm:2.0.4, turbo-darwin-arm64@npm:2.0.4, turbo-linux-64@npm:2.0.4, turbo-linux-arm64@npm:2.0.4, and 2 more.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 2 packages were added to the project (+ 17.96 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 168ms

 WARNING  No locally installed `turbo` found. Using version: 2.0.4.
• Packages in scope: @openmobilehub/auth-core, @openmobilehub/auth-dropbox, @openmobilehub/auth-facebook, @openmobilehub/auth-google, @openmobilehub/auth-microsoft, react-native-omh-auth-sample
• Running build in 6 packages
• Remote caching disabled
┌ @openmobilehub/auth-core#build > cache miss, executing b21f7a527bcfd98e
│ /Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/cliui/build/index.cjs:291
│ const stringWidth = require('string-width');
│                     ^
│
│ Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/string-width/index.js from
│  /Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/cliui/build/index.cjs not supported.
│ Instead change the require of index.js in /Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/cliui/build/index.cjs to a dynam
│ ic import() which is available in all CommonJS modules.
│     at Object.<anonymous> (/Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/cliui/build/index.cjs:291:21)
│     at Object.<anonymous> (/Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/yargs/build/index.cjs:1:60678)
│     at Object.<anonymous> (/Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/yargs/index.cjs:5:30)
│     at Object.<anonymous> (/Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/react-native-builder-bob/lib/index.js:7:37)
│     at Object.<anonymous> (/Users/xxxxxxxx/tools/git/react-native-omh-auth/node_modules/react-native-builder-bob/bin/bob:4:1) {
│   code: 'ERR_REQUIRE_ESM'
│ }
│
│ Node.js v18.17.1
│ command finished with error: command (/Users/xxxxxxxx/tools/git/react-native-omh-auth/packages/core) /private/var/folders/k7/rfqbzwt91w
│ bfbf96zd5g1tw00000gn/T/xfs-de5f562c/yarn run build exited (1)
└────>
 ERROR  run failed: command  exited (1)
```

Am I missing anything?

**Comment by andrei-zgirvaci** [comment]
@dzuluaga Could you try to delete the root project **node_modules**, **/docs/node_modules** and run `yarn install && yarn build && yarn workspace docs start` from the root project directory, **not** the **/docs** directory?

**Comment by dzuluaga** [comment]
Thank you, @andrei-zgirvaci. The commands work perfectly when run from the root folder. I appreciate the update to the documentation. 

I have one suggestion: to make it more prominent to users that these commands should be run from the root folder. I noticed two places where this could be improved: `CONTRIBUTING.md` and `doc/README.md`.

### Installation

To get started with the project, run the following command in the root directory to install the required dependencies for each package:

⚠️ **Important:** Run the following command **in the root folder**:

```
$ yarn
```

**Comment by adamTrz** [comment]
Looks like we've already added `yarn` command to the docs :) 

Readme | Contributing 
--- | ---
<img width="651" alt="image" src="https://github.com/openmobilehub/react-native-omh-auth/assets/13610886/cf6fbea3-4a7f-4403-9360-476acc1a3a48"> | <img width="621" alt="image" src="https://github.com/openmobilehub/react-native-omh-auth/assets/13610886/b79167e3-069b-4019-b4e5-cab20a3d7e4b">

Closing the issue but please reopen if it reappears :)
